project:
  type: website
  # post-render: 
  #   cp _index.html docs/index.html


# website:
#   navbar:
    # tools:
    #   - icon: globe
    #     menu:
    #       - text: English
    #         href: ../en
    #       - text: German
    #         href: ../de


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

profile:
  group: 
    - [en, de]

