project:
  type: website
  post-render: 
    cp _index.html docs/index.html


website:
  navbar:
    tools:
      - icon: globe
        menu:
          - text: English
            href: ../en
          - text: German
            href: ../de
    right:
      - href: ../de
        text: Deutsch
      - href: ../en
        text: '<span id="btn-en">English</span>'

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

profile:
  group: 
    - [en, de]

